name: PHP Composer Install

# Menentukan kapan workflow akan dijalankan
on:
  push:
    branches:
      - main  # Menjalankan workflow saat ada push ke branch 'main'
  pull_request:
    branches:
      - main  # Menjalankan workflow saat ada pull request ke branch 'main'

jobs:
  install:
    runs-on: ubuntu-latest  # Menjalankan job di runner Ubuntu terbaru

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2  # Mengambil kode dari repository

    # Step 2: Set up PHP (menggunakan versi PHP tertentu)
    - name: Set up PHP
      uses: shivammathur/setup-php@v2  # Menggunakan aksi untuk mengatur PHP
      with:
        php-version: '7.4'  # Anda bisa memilih versi PHP sesuai dengan kebutuhan
        extensions: mbstring, mysqli, curl  # Tambahkan ekstensi PHP yang dibutuhkan
        coverage: none  # Tidak perlu laporan coverage untuk ini

    # Step 3: Install Composer (jika belum terinstal)
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php  # Mengunduh dan menginstal Composer
        php composer.phar install --no-progress --prefer-dist  # Menjalankan composer install untuk menginstal dependensi

    # Step 4: Verifikasi instalasi (opsional)
    - name: Verify Composer Install
      run: |
        php composer.phar show  # Menampilkan daftar paket yang terinstal
