# GitHub Actions workflow untuk Build dan Deploy aplikasi PHP ke Azure Web App

name: Build and deploy PHP app to Azure Web App - libraryazul

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Langkah 2: Setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, curl, mysqli

      # Langkah 3: Install dependencies dengan Composer (jika ada composer.json)
      - name: Install Dependencies with Composer
        if: exists('composer.json')
        run: |
          composer install --no-dev --optimize-autoloader

      # Langkah 4: Buat file zip untuk deployment
      - name: Archive the App for Deployment
        run: zip -r app.zip ./

      # Langkah 5: Login ke Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Langkah 6: Deploy ke Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'libraryazul'
          slot-name: 'production'
          package: app.zip
